services:
  api:
    build: .
    network_mode: host
    environment:
      - REDIS_URL=redis://localhost:6379
      - MQTT_BROKER=localhost
      - MQTT_PORT=1883
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    restart: unless-stopped
    depends_on:
      - redis
      - mqtt

  mqtt:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto_data:/mosquitto
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
  mosquitto_data:
